import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';
import { Router, RouterModule } from '@angular/router';
import { ToastService } from '../../services/toast.service';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css'],
})
export class RegisterComponent {
  private toastService = inject(ToastService);
  isLoading = true;
  message = '';
  errorMessage = '';
  successMessage = '';

  countries: string[] = [
    'Αφγανιστάν',
'Αλβανία',
'Αλγερία',
'Ανδόρα',
'Ανγκόλα',
'Αργεντινή',
'Αρμενία',
'Αυστραλία',
'Αυστρία',
'Αζερμπαϊτζάν',
'Μπαχάμες',
'Μπαχρέιν',
'Μπανγκλαντές',
'Μπαρμπάντος',
'Λευκορωσία',
'Βέλγιο',
'Μπελίζ',
'Μπενίν',
'Μπουτάν',
'Βολιβία',
'Βοσνία και Ερζεγοβίνη',
'Μποτσουάνα',
'Βραζιλία',
'Μπρουνέι',
'Βουλγαρία',
'Μπουρκίνα Φάσο',
'Μπουρούντι',
'Πράσινο Ακρωτήριο',
'Καμπότζη',
'Καμερούν',
'Καναδάς',
'Κεντροαφρικανική Δημοκρατία',
'Τσαντ',
'Χιλή',
'Κίνα',
'Κολομβία',
'Κομόρες',
'Κονγκό',
'Κόστα Ρίκα',
'Κροατία',
'Κούβα',
'Κύπρος',
'Τσεχία',
'Δανία',
'Τζιμπουτί',
'Ντομίνικα',
'Δομινικανή Δημοκρατία',
'Ανατολικό Τιμόρ',
'Εκουαδόρ',
'Αίγυπτος',
'Ελ Σαλβαδόρ',
'Ισημερινή Γουινέα',
'Ερυθραία',
'Εσθονία',
'Εσουατίνι',
'Αιθιοπία',
'Φίτζι',
'Φινλανδία',
'Γαλλία',
'Γκαμπόν',
'Γκάμπια',
'Γεωργία',
'Γερμανία',
'Γκάνα',
'Ελλάδα',
'Γρενάδα',
'Γουατεμάλα',
'Γουινέα',
'Γουινέα-Μπισάου',
'Γουιάνα',
'Αϊτή',
'Ονδούρα',
'Ουγγαρία',
'Ισλανδία',
'Ινδία',
'Ινδονησία',
'Ιράν',
'Ιράκ',
'Ιρλανδία',
'Ισραήλ',
'Ιταλία',
'Ακτή Ελεφαντοστού',
'Τζαμάικα',
'Ιαπωνία',
'Ιορδανία',
'Καζακστάν',
'Κένυα',
'Κιριμπάτι',
'Βόρεια Κορέα',
'Νότια Κορέα',
'Κόσοβο',
'Κουβέιτ',
'Κιργιστάν',
'Λάος',
'Λετονία',
'Λίβανος',
'Λεσότο',
'Λιβερία',
'Λιβύη',
'Λιχτενστάιν',
'Λιθουανία',
'Λουξεμβούργο',
'Μαδαγασκάρη',
'Μαλάουι',
'Μαλαισία',
'Μαλδίβες',
'Μάλι',
'Μάλτα',
'Νησιά Μάρσαλ',
'Μαυριτανία',
'Μαυρίκιος',
'Μεξικό',
'Μικρονησία',
'Μολδαβία',
'Μονακό',
'Μογγολία',
'Μαυροβούνιο',
'Μαρόκο',
'Μοζαμβίκη',
'Μιανμάρ',
'Ναμίμπια',
'Ναούρου',
'Νεπάλ',
'Ολλανδία',
'Νέα Ζηλανδία',
'Νικαράγουα',
'Νίγηρας',
'Νιγηρία',
'Βόρεια Μακεδονία',
'Νορβηγία',
'Ομάν',
'Πακιστάν',
'Παλάου',
'Παναμάς',
'Παπούα Νέα Γουινέα',
'Παραγουάη',
'Περού',
'Φιλιππίνες',
'Πολωνία',
'Πορτογαλία',
'Κατάρ',
'Ρουμανία',
'Ρωσία',
'Ρουάντα',
'Άγιος Χριστόφορος και Νέβις',
'Αγία Λουκία',
'Άγιος Βικέντιος και Γρεναδίνες',
'Σαμόα',
'Άγιος Μαρίνος',
'Σάο Τομέ και Πρίνσιπε',
'Σαουδική Αραβία',
'Σενεγάλη',
'Σερβία',
'Σεϋχέλλες',
'Σιέρα Λεόνε',
'Σιγκαπούρη',
'Σλοβακία',
'Σλοβενία',
'Νησιά Σολομώντος',
'Σομαλία',
'Νότια Αφρική',
'Ισπανία',
'Σρι Λάνκα',
'Σουδάν',
'Σουρινάμ',
'Σουηδία',
'Ελβετία',
'Συρία',
'Ταϊβάν',
'Τατζικιστάν',
'Τανζανία',
'Ταϊλάνδη',
'Τόγκο',
'Τόνγκα',
'Τρινιντάντ και Τομπάγκο',
'Τυνησία',
'Τουρκία',
'Τουρκμενιστάν',
'Τουβαλού',
'Ουγκάντα',
'Ουκρανία',
'Ηνωμένα Αραβικά Εμιράτα',
'Ηνωμένο Βασίλειο',
'Ηνωμένες Πολιτείες',
'Ουρουγουάη',
'Ουζμπεκιστάν',
'Βανουάτου',
'Βατικανό',
'Βενεζουέλα',
'Βιετνάμ',
'Υεμένη',
'Ζάμπια',
'Ζιμπάμπουε',
  ];

  registerObj = {
    username: '',
    firstName: '',
    lastName: '',
    email: '',
    password: '',
    confirmPassword: '',
    country: '',
    city: '',
    gender: 'Male',
    dateOfBirth: '',
  };

  constructor(
    private auth: AuthService,
    private router: Router,
  ) {}

  onRegister() {
    if (this.registerObj.password !== this.registerObj.confirmPassword) {
      this.errorMessage = 'Οι κωδικοί δεν ταιριάζουν!';
      return;
    }

    const dataToSend = {
      username: this.registerObj.username,
      firstName: this.registerObj.firstName,
      lastName: this.registerObj.lastName,
      email: this.registerObj.email,
      password: this.registerObj.password,
      country: this.registerObj.country,
      city: this.registerObj.city,
      gender: this.registerObj.gender,
      dateOfBirth: this.registerObj.dateOfBirth,
    };

    this.auth.register(dataToSend).subscribe({
      next: (res) => {
        this.isLoading = true;
        this.toastService.showSuccess('Η εγγραφή πέτυχε!');
        this.router.navigate(['/mainapp']);
        setTimeout(() => {
          this.router.navigate(['/login']);
        }, 3000);
      },
      error: (err) => {
        this.isLoading = false;
        console.log(err);
        this.errorMessage = err.error;
        this.toastService.showError('Κάτι πήγε στραβά κατά την εγγραφή.');
      },
    });
  }
}
